services:
  nebula-ticket:
    container_name: nebula-ticket
    build:
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
        POSTGRES_URL_NON_POOLING: ${POSTGRES_URL_NON_POOLING}
        NEXT_PUBLIC_NEBULA_ASSETS_URL: ${NEXT_PUBLIC_NEBULA_ASSETS_URL}
    restart: always
    ports:
      - "${APP_PORT:-3001}:3000"
    environment:
      - DATABASE_URL
      - POSTGRES_PRISMA_URL
      - POSTGRES_URL_NON_POOLING
      - AUTH_SECRET
      - NEXT_PUBLIC_NEBULA_ASSETS_URL
      - APP_URL
      - AUTH_TRUST_HOST
      - AUTH_URL
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
